-- Title: Data Science Skills
-- Company: LinkedIn
-- Difficulty: Easy
-- Access: Free
-- Pattern: conditional aggregation
-- Summary: Count or flag required skills per candidate using CASE expressions, then filter for those meeting the full skill set.
-- Notes: Use COUNT(DISTINCT skill) if duplicates exist; ensure case-insensitive matching if skills vary in capitalization.
-- Dialect: PostgreSQL
