-- Title: Average Post Hiatus (Part 1)
-- Company: Facebook
-- Difficulty: Easy
-- Access: Free
-- Pattern: window function (LAG) + date difference
-- Summary: Compute the day gaps between consecutive posts per user using LAG, then take the average hiatus length.
-- Notes: Order strictly by post date/time; exclude the first post per user (NULL gap) from the average.
-- Dialect: PostgreSQL
