-- Title: Teams Power Users
-- Company: Microsoft
-- Difficulty: Easy
-- Access: Free
-- Pattern: aggregation + HAVING threshold
-- Summary: Aggregate user activity and filter users who exceed a power-user threshold using HAVING.
-- Notes: Use COUNT(DISTINCT ...) if the metric is unique actions; confirm the threshold metric (messages, reactions, days active).
-- Dialect: PostgreSQL
