-- Title: Duplicate Job Listings
-- Company: LinkedIn
-- Difficulty: Easy
-- Access: Free
-- Pattern: duplicate detection (GROUP BY + HAVING)
-- Summary: Identify duplicate job listings by grouping on the fields that define “same listing” and filtering groups with count > 1.
-- Notes: Use COUNT(*) for duplicates; if output needs unique companies/roles, select the grouping columns (not raw rows).
-- Dialect: PostgreSQL
