-- Title: Well Paid Employees
-- Company: FAANG
-- Difficulty: Easy
-- Access: Free
-- Pattern: filtering with aggregate benchmark
-- Summary: Compare employee pay against a benchmark (e.g., department average) and return employees meeting the “well paid” condition.
-- Notes: If benchmark is per-department, compute it in a CTE/subquery then join back; ensure correct comparison operator.
-- Dialect: PostgreSQL
