-- Title: Final Account Balance
-- Company: PayPal
-- Difficulty: Easy
-- Access: Free
-- Pattern: signed aggregation (credits vs debits)
-- Summary: Compute ending balances by summing transaction amounts with correct signs for inflows vs outflows.
-- Notes: Use CASE to assign +/- amounts; confirm which column indicates sender vs receiver (or transaction type).
-- Dialect: PostgreSQL
