-- Title: App Click-through Rate (CTR)
-- Company: Facebook
-- Difficulty: Easy
-- Access: Free
-- Pattern: conditional aggregation (rate)
-- Summary: Compute CTR as clicks divided by impressions (or views) using conditional counts/sums and a ratio.
-- Notes: Cast to numeric to avoid integer division; protect against divide-by-zero with NULLIF.
-- Dialect: PostgreSQL
