-- Title: Second Day Confirmation
-- Company: TikTok
-- Difficulty: Easy
-- Access: Free
-- Pattern: retention / cohort check (self-join or date diff)
-- Summary: Identify users who returned/confirmed on day 2 by comparing event dates to the signup/initial date.
-- Notes: Use DATE + INTERVAL '1 day' or date_diff logic; ensure you’re matching the correct “day 2” definition.
-- Dialect: PostgreSQL
