-- Title: IBM db2 Product Analytics
-- Company: IBM
-- Difficulty: Easy
-- Access: Free
-- Pattern: aggregation by dimension
-- Summary: Aggregate product usage/engagement metrics by the required dimension (e.g., user, product, date) and return the requested summary.
-- Notes: Apply the correct filters first (date range, product name, event type) before aggregating.
-- Dialect: PostgreSQL
