-- Title: Pharmacy Analytics (Part 2)
-- Company: CVS Health
-- Difficulty: Easy
-- Access: Free
-- Pattern: aggregation + join
-- Summary: Join relevant tables (e.g., prescriptions, patients) then compute the requested aggregate metrics.
-- Notes: Watch for one-to-many joins that inflate counts; use DISTINCT where needed to avoid double-counting.
-- Dialect: PostgreSQL
