-- Title: Pharmacy Analytics (Part 3)
-- Company: CVS Health
-- Difficulty: Easy
-- Access: Free
-- Pattern: conditional aggregation
-- Summary: Compute segmented pharmacy metrics using CASE expressions and aggregate to produce the requested breakdown.
-- Notes: Ensure categories are mutually exclusive; cast to numeric for ratios to avoid integer division.
-- Dialect: PostgreSQL
