-- Title: Most Expensive Purchase
-- Company: Amazon
-- Difficulty: Easy
-- Access: Premium
-- Pattern: top-1 per group (window rank or MAX)
-- Summary: Identify the most expensive purchase by selecting the maximum purchase amount (optionally per user) and returning the matching record(s).
-- Notes: If ties are possible, use RANK/DENSE_RANK to keep all top purchases; confirm whether output is global or per-user.
-- Dialect: PostgreSQL
