-- Title: Subject Matter Experts
-- Company: Accenture
-- Difficulty: Easy
-- Access: Premium
-- Pattern: aggregation + HAVING
-- Summary: Identify experts by aggregating experience/skills per employee and filtering those meeting an expertise threshold.
-- Notes: Use COUNT(DISTINCT skill) if duplicates exist; confirm whether threshold is per-skill, per-project, or total.
-- Dialect: PostgreSQL
