-- Title: LinkedIn Power Creators (Part 1)
-- Company: LinkedIn
-- Difficulty: Easy
-- Access: Premium
-- Pattern: aggregation + threshold
-- Summary: Aggregate creator activity metrics and filter to power creators who exceed a defined engagement or posting threshold.
-- Notes: Verify the metric definition (posts, reactions, followers, impressions); use COUNT(DISTINCT ...) to avoid double-counting.
-- Dialect: PostgreSQL
