-- Title: Spare Server Capacity
-- Company: Microsoft
-- Difficulty: Easy
-- Access: Premium
-- Pattern: aggregation + capacity math
-- Summary: Compute spare capacity by aggregating used resources per server and subtracting from total capacity.
-- Notes: Use COALESCE to treat missing usage as 0; ensure units match (CPU, memory, etc.).
-- Dialect: PostgreSQL
