-- Title: Trade In Payouts
-- Company: Apple
-- Difficulty: Easy
-- Access: Premium
-- Pattern: conditional aggregation + grouping
-- Summary: Compute trade-in payout totals by grouping on the required dimension and summing payout amounts.
-- Notes: If payout depends on condition/grade, use CASE logic; handle NULL payouts with COALESCE if needed.
-- Dialect: PostgreSQL
