-- Title: Webinar Popularity
-- Company: Snowflake
-- Difficulty: Easy
-- Access: Premium
-- Pattern: aggregation + ranking
-- Summary: Aggregate webinar attendance/engagement metrics and rank webinars to identify the most popular ones.
-- Notes: If popularity is based on distinct attendees, use COUNT(DISTINCT user_id); include ties with DENSE_RANK if needed.
-- Dialect: PostgreSQL
