-- Title: Who Made Quota?
-- Company: Oracle
-- Difficulty: Easy
-- Access: Premium
-- Pattern: aggregation + threshold (HAVING)
-- Summary: Aggregate sales per rep and filter for those who meet or exceed quota using HAVING.
-- Notes: Ensure sales are summed over the correct time period; use COALESCE if sales can be NULL.
-- Dialect: PostgreSQL
