-- Title: Active User Retention
-- Company: Facebook
-- Difficulty: Hard
-- Access: Free
-- Pattern: retention cohort (self-join / window)
-- Summary: Compute retention by cohorting users on an initial activity date and measuring return activity in subsequent periods.
-- Notes: Define cohort date consistently; use COUNT(DISTINCT user_id); align time buckets (day/week) exactly to the definition.
-- Dialect: PostgreSQL
