-- Title: Y-on-Y Growth Rate
-- Company: Wayfair
-- Difficulty: Hard
-- Access: Free
-- Pattern: time series growth (LAG) + percent change
-- Summary: Compute year-over-year growth by comparing each period’s metric to the same period in the prior year.
-- Notes: Aggregate to the correct grain first; use LAG(…, 12) for monthly or join on year-1; use NULLIF to avoid divide-by-zero.
-- Dialect: PostgreSQL
