-- Title: Maximize Prime Item Inventory
-- Company: Amazon
-- Difficulty: Hard
-- Access: Free
-- Pattern: constraints + window ranking
-- Summary: Allocate limited inventory to maximize Prime eligibility by ranking items/warehouses and selecting optimal assignments under constraints.
-- Notes: Break into CTEs; ensure constraints are enforced once; window ranking helps pick best candidates per constraint group.
-- Dialect: PostgreSQL
