-- Title: Median Google Search Frequency
-- Company: Google
-- Difficulty: Hard
-- Access: Free
-- Pattern: median via percentile / ranking
-- Summary: Compute the median search frequency by ordering user frequencies and applying percentile logic.
-- Notes: PostgreSQL supports PERCENTILE_CONT; if building manually, use row_number and middle-position logic; handle even counts carefully.
-- Dialect: PostgreSQL
