-- Title: Advertiser Status
-- Company: Facebook
-- Difficulty: Hard
-- Access: Free
-- Pattern: state classification (business rules)
-- Summary: Classify advertisers into statuses based on activity thresholds and time windows using conditional logic over aggregates.
-- Notes: Encode status rules with CASE; ensure correct time filtering and distinct counts to avoid double-counting events.
-- Dialect: PostgreSQL
