-- Title: Consecutive Filing Years
-- Company: Intuit
-- Difficulty: Hard
-- Access: Free
-- Pattern: gaps-and-islands (consecutive years)
-- Summary: Detect consecutive filing streaks by comparing each year to the prior year per user and grouping continuous sequences.
-- Notes: Use LAG(year) and a running group id; handle duplicates per year with DISTINCT; filter to streak length as required.
-- Dialect: PostgreSQL
