-- Title: Marketing Touch Streak
-- Company: Snowflake
-- Difficulty: Hard
-- Access: Free
-- Pattern: streaks (gaps-and-islands)
-- Summary: Compute longest or current marketing touch streaks by grouping consecutive touch dates per customer.
-- Notes: Deduplicate multiple touches on the same day if needed; use date difference logic + running group id to form streaks.
-- Dialect: PostgreSQL
