-- Title: 3-Topping Pizzas
-- Company: McKinsey
-- Difficulty: Hard
-- Access: Free
-- Pattern: combinations via self-join
-- Summary: Generate unique 3-item topping combinations using ordered self-joins and return all valid distinct combos.
-- Notes: Enforce ordering (t1 < t2 < t3) to avoid permutations; use DISTINCT to remove duplicates.
-- Dialect: PostgreSQL
