-- Title: Patient Support Analysis (Part 3)
-- Company: UnitedHealth
-- Difficulty: Hard
-- Access: Free
-- Pattern: multi-step aggregation + segmentation
-- Summary: Extend patient support analysis with advanced segmentation/window logic to compute the requested metrics and breakdowns.
-- Notes: Use CTEs to stage logic; ensure joins don’t inflate counts; match filtering criteria exactly to the definition.
-- Dialect: PostgreSQL
