-- Title: Patient Support Analysis (Part 4)
-- Company: UnitedHealth
-- Difficulty: Hard
-- Access: Free
-- Pattern: multi-step aggregation + window
-- Summary: Compute advanced patient support metrics using multiple CTE stages and window functions as required by the final output.
-- Notes: Validate intermediate outputs; ensure correct partitioning/order for windows; handle NULLs and duplicates carefully.
-- Dialect: PostgreSQL
