-- Title: Reactivated Users
-- Company: Facebook
-- Difficulty: Hard
-- Access: Free
-- Pattern: churn/reactivation (gaps in activity)
-- Summary: Identify users who became inactive for a period and later returned, based on gaps between activity dates.
-- Notes: Compute last-active and next-active dates; define inactivity threshold precisely; deduplicate multiple events per day if needed.
-- Dialect: PostgreSQL
