-- Title: Senior Managers
-- Company: Google
-- Difficulty: Hard
-- Access: Free
-- Pattern: hierarchical self-join + aggregation
-- Summary: Use manager-employee hierarchy to count reports (direct/indirect) and return managers meeting the senior threshold.
-- Notes: Recursive CTE may be required for indirect reports; avoid cycles; count DISTINCT employees to prevent double-counting.
-- Dialect: PostgreSQL
