-- Title: Server Utilization Time
-- Company: Amazon
-- Difficulty: Hard
-- Access: Free
-- Pattern: interval overlap + aggregation
-- Summary: Compute server utilization by merging overlapping time intervals per server and summing total utilized time.
-- Notes: Use gaps-and-islands on interval boundaries; handle overlaps/adjacent intervals; ensure consistent time units.
-- Dialect: PostgreSQL
