-- Title: Compressed Median
-- Company: Alibaba
-- Difficulty: Hard
-- Access: Premium
-- Pattern: weighted median (frequency table)
-- Summary: Compute the median from a frequency table by finding the smallest value where cumulative frequency reaches 50% of total.
-- Notes: Use running SUM(frequency) over ordered values; handle even totals carefully per definition; watch off-by-one in thresholds.
-- Dialect: PostgreSQL
