-- Title: Average Vacant Days
-- Company: Airbnb
-- Difficulty: Hard
-- Access: Premium
-- Pattern: date gaps (availability intervals)
-- Summary: Compute average vacant days by measuring gaps between booked intervals per listing and averaging vacancy durations.
-- Notes: Sort bookings per listing; clamp overlaps; decide whether to include leading/trailing vacancy based on definition.
-- Dialect: PostgreSQL
