-- Title: Same Week Purchases
-- Company: Etsy
-- Difficulty: Hard
-- Access: Premium
-- Pattern: time bucketing + self-join / aggregation
-- Summary: Identify users who made multiple purchases within the same week by bucketing purchases to week and filtering for repeats.
-- Notes: Use DATE_TRUNC('week', ...) for week bucket; ensure week definition matches expected (Mon vs Sun start).
-- Dialect: PostgreSQL
