-- Title: Follow-Up Airpod Percentage
-- Company: Apple
-- Difficulty: Hard
-- Access: Premium
-- Pattern: cohort + conditional percentage
-- Summary: Compute the percentage of users who made a follow-up AirPods purchase after an initial qualifying purchase/event.
-- Notes: Define the qualifying first event precisely; use DISTINCT users; use NULLIF to avoid divide-by-zero; handle time window boundaries.
-- Dialect: PostgreSQL
