-- Title: FAANG Underperforming Stocks (Part 3)
-- Company: Bloomberg
-- Difficulty: Hard
-- Access: Premium
-- Pattern: time series benchmark comparison
-- Summary: Identify underperforming stocks by computing returns over a period and comparing them against a benchmark/peer threshold.
-- Notes: Ensure consistent period endpoints; handle missing months/days; cast to numeric for return calculations.
-- Dialect: PostgreSQL
