-- Title: User Concurrent Sessions
-- Company: Pinterest
-- Difficulty: Hard
-- Access: Premium
-- Pattern: concurrency (sweep line on intervals)
-- Summary: Compute maximum concurrent sessions by converting session intervals into start/+1 and end/-1 events and taking a running sum.
-- Notes: Order ties correctly (end before start at same timestamp if required); use window SUM over ordered events to get concurrency.
-- Dialect: PostgreSQL
