-- Title: Bad Delivery Rate
-- Company: DoorDash
-- Difficulty: Hard
-- Access: Premium
-- Pattern: conditional aggregation (rate) + filtering
-- Summary: Compute bad delivery rate by dividing bad deliveries by total deliveries over the defined window and grouping as required.
-- Notes: Define “bad” precisely (late, canceled, wrong order, etc.); cast to numeric and use NULLIF to avoid divide-by-zero.
-- Dialect: PostgreSQL
