-- Title: Page Recommendation
-- Company: Facebook
-- Difficulty: Hard
-- Access: Premium
-- Pattern: graph recommendation (friends/likes) + ranking
-- Summary: Recommend pages by leveraging user-user connections and page interactions, scoring candidate pages and ranking the top suggestions.
-- Notes: Exclude pages the user already likes; deduplicate candidates; use window ranking to return top-N per user.
-- Dialect: PostgreSQL
