-- Title: Event Friends Recommendation
-- Company: Facebook
-- Difficulty: Hard
-- Access: Premium
-- Pattern: graph recommendation + filtering
-- Summary: Recommend friends for events by combining friendship edges with event participation signals and ranking candidates.
-- Notes: Exclude existing attendees/invitees per definition; avoid double-counting mutual connections; use DISTINCT on candidate pairs.
-- Dialect: PostgreSQL
