-- Title: Matching Rental Amenities
-- Company: Airbnb
-- Difficulty: Hard
-- Access: Premium
-- Pattern: set containment (relational division)
-- Summary: Find rentals that contain all required amenities by grouping amenities per listing and filtering with HAVING.
-- Notes: Use COUNT(DISTINCT amenity) = required_count; ensure required list is deduplicated; join conditions must be exact.
-- Dialect: PostgreSQL
