-- Title: Weekly Churn Rates
-- Company: Facebook
-- Difficulty: Hard
-- Access: Premium
-- Pattern: churn / retention time series
-- Summary: Compute weekly churn by comparing active users week-over-week and counting users who drop off in the next week.
-- Notes: Define “active” per week consistently; use DATE_TRUNC('week', ...); COUNT(DISTINCT user_id); handle partial weeks carefully.
-- Dialect: PostgreSQL
