-- Title: Uniquely Staffed Consultants
-- Company: Accenture
-- Difficulty: Hard
-- Access: Premium
-- Pattern: set uniqueness + aggregation
-- Summary: Identify consultants staffed in a unique way by aggregating staffing assignments and filtering to those whose assignment set is unique.
-- Notes: Build a canonical representation of assignment sets (e.g., STRING_AGG ordered) or compare counts per project; watch for duplicates.
-- Dialect: PostgreSQL
