-- Title: User's Third Transaction
-- Company: Uber
-- Difficulty: Medium
-- Access: Free
-- Pattern: window function (ROW_NUMBER)
-- Summary: Order transactions per user and select the third one using ROW_NUMBER (or another ranking window function).
-- Notes: Use a deterministic order (timestamp + transaction_id) to break ties; filter row_number = 3.
-- Dialect: PostgreSQL
