-- Title: Sending vs. Opening Snaps
-- Company: Snapchat
-- Difficulty: Medium
-- Access: Free
-- Pattern: conditional aggregation
-- Summary: Compare sending vs opening behavior by aggregating counts per user (or date) using CASE filters for each action type.
-- Notes: Ensure event/action labels match exactly; if comparing rates, cast to numeric and use NULLIF for divide-by-zero.
-- Dialect: PostgreSQL
