-- Title: Tweets' Rolling Averages
-- Company: Twitter
-- Difficulty: Medium
-- Access: Free
-- Pattern: window function (rolling average)
-- Summary: Compute a rolling average of tweet counts per user over a 3-day window using an ordered window frame.
-- Notes: Order by date; ensure the window frame matches the exact definition (ROWS vs RANGE); round only if required.
-- Dialect: PostgreSQL
