-- Title: Highest-Grossing Items
-- Company: Amazon
-- Difficulty: Medium
-- Access: Free
-- Pattern: aggregation + ranking (top-N)
-- Summary: Aggregate revenue per item and return the highest-grossing items using ORDER BY with LIMIT or window ranking.
-- Notes: Revenue may require SUM(price * quantity); handle ties with DENSE_RANK if the expected output includes them.
-- Dialect: PostgreSQL
