-- Title: Top Three Salaries
-- Company: FAANG
-- Difficulty: Medium
-- Access: Free
-- Pattern: window function (DENSE_RANK) / top-N
-- Summary: Return the top three distinct salaries (optionally per department) using DENSE_RANK and filtering rank <= 3.
-- Notes: Use DENSE_RANK (not ROW_NUMBER) to keep ties; clarify whether scope is company-wide or per department.
-- Dialect: PostgreSQL
