-- Title: Spotify Streaming History
-- Company: Spotify
-- Difficulty: Medium
-- Access: Free
-- Pattern: aggregation + grouping (time series)
-- Summary: Aggregate streaming activity by the required dimension (e.g., user, artist, date) to produce a listening-history summary.
-- Notes: If session boundaries matter, group by date/time correctly; watch for duplicates and use DISTINCT where needed.
-- Dialect: PostgreSQL
