-- Title: Supercloud Customer
-- Company: Microsoft
-- Difficulty: Medium
-- Access: Free
-- Pattern: set logic (HAVING across categories)
-- Summary: Identify customers who purchased across all required product categories by grouping and filtering with HAVING.
-- Notes: Use COUNT(DISTINCT category) = N to enforce “all categories”; ensure category mapping matches the definition.
-- Dialect: PostgreSQL
