-- Title: Odd and Even Measurements
-- Company: Google
-- Difficulty: Medium
-- Access: Free
-- Pattern: window function + conditional aggregation
-- Summary: Assign an order to measurements per day and sum values at odd vs even positions using window functions.
-- Notes: Use ROW_NUMBER ordered by time; then SUM with CASE for odd/even; ensure ordering is deterministic.
-- Dialect: PostgreSQL
