-- Title: Swapped Food Delivery
-- Company: Zomato
-- Difficulty: Medium
-- Access: Free
-- Pattern: self-join / pairing logic
-- Summary: Detect swapped deliveries by matching orders and deliveries across users/restaurants and flagging mismatched pairings.
-- Notes: Be careful with join keys to avoid Cartesian matches; use DISTINCT or a unique order id where available.
-- Dialect: PostgreSQL
