-- Title: FAANG Stock Min-Max (Part 1)
-- Company: Bloomberg
-- Difficulty: Medium
-- Access: Free
-- Pattern: aggregation (MIN/MAX) over time
-- Summary: Compute min and max stock prices (or values) per ticker over the specified time window.
-- Notes: Filter to the correct date range first; group by ticker; ensure using the correct price column.
-- Dialect: PostgreSQL
