-- Title: User Shopping Sprees
-- Company: Amazon
-- Difficulty: Medium
-- Access: Free
-- Pattern: window function (LAG) + streak/sessionization
-- Summary: Identify shopping sprees by ordering purchases per user and grouping sequences where gaps between purchases meet the spree condition.
-- Notes: Use LAG to compute time gaps; create a running group id via cumulative sum; confirm gap threshold and units.
-- Dialect: PostgreSQL
