-- Title: Histogram of Users and Purchases
-- Company: Walmart
-- Difficulty: Medium
-- Access: Free
-- Pattern: two-step aggregation (histogram)
-- Summary: Aggregate purchase counts per user, then count users per purchase-count bucket to produce a histogram.
-- Notes: Use COUNT(DISTINCT order_id) if multiple rows per order exist; filter to the correct timeframe before aggregation.
-- Dialect: PostgreSQL
