-- Title: Card Launch Success
-- Company: JPMorgan
-- Difficulty: Medium
-- Access: Free
-- Pattern: aggregation + conditional logic
-- Summary: Evaluate card launch success by aggregating performance metrics and applying the success criteria.
-- Notes: Implement criteria with CASE; ensure you’re aggregating at the correct grain (card, launch cohort, date).
-- Dialect: PostgreSQL
