-- Title: International Call Percentage
-- Company: Verizon
-- Difficulty: Medium
-- Access: Free
-- Pattern: conditional aggregation (percentage)
-- Summary: Compute the percentage of international calls by dividing international call counts by total calls.
-- Notes: Use NULLIF to avoid divide-by-zero; confirm what defines “international” (country codes vs boolean flag).
-- Dialect: PostgreSQL
