-- Title: Patient Support Analysis (Part 2)
-- Company: UnitedHealth
-- Difficulty: Medium
-- Access: Free
-- Pattern: aggregation + window / segmentation
-- Summary: Extend the patient support analysis by computing segmented metrics and returning the required breakdown.
-- Notes: Watch for one-to-many joins inflating counts; use DISTINCT where appropriate; match exact filtering criteria.
-- Dialect: PostgreSQL
