-- Title: Fill Missing Client Data
-- Company: Accenture
-- Difficulty: Medium
-- Access: Premium
-- Pattern: data imputation (window fill / self-join)
-- Summary: Fill missing client fields by carrying forward/backward known values within each client using window functions or joins.
-- Notes: Define fill direction explicitly (last known vs next known); be careful not to mix clients; COALESCE is typically used.
-- Dialect: PostgreSQL
