-- Title: Mean, Median, Mode
-- Company: Microsoft
-- Difficulty: Medium
-- Access: Premium
-- Pattern: descriptive statistics (aggregate + percentile)
-- Summary: Compute mean/median/mode using AVG, percentile logic for median, and frequency ranking for mode.
-- Notes: Median often uses PERCENTILE_CONT; mode requires handling ties via DENSE_RANK; cast to numeric to avoid integer division.
-- Dialect: PostgreSQL
