-- Title: Pharmacy Analytics (Part 4)
-- Company: CVS Health
-- Difficulty: Medium
-- Access: Premium
-- Pattern: multi-step aggregation
-- Summary: Combine prior pharmacy metrics with additional filters/joins and compute the requested summary measures.
-- Notes: Stage logic in CTEs to avoid double-counting; apply cohort/date filters early for performance.
-- Dialect: PostgreSQL
