-- Title: Frequently Purchased Pairs
-- Company: Walmart
-- Difficulty: Medium
-- Access: Premium
-- Pattern: self-join pairs + aggregation
-- Summary: Generate item pairs from the same order/cart via self-join, then count pair frequency to find top pairs.
-- Notes: Enforce item_a < item_b to avoid duplicates; use COUNT(DISTINCT order_id) if multiple rows per order exist.
-- Dialect: PostgreSQL
