-- Title: Booking Referral Source
-- Company: Airbnb
-- Difficulty: Medium
-- Access: Premium
-- Pattern: attribution aggregation
-- Summary: Attribute bookings to referral sources and aggregate bookings/revenue by source.
-- Notes: If multiple touches exist, confirm whether to use first-touch/last-touch; deduplicate bookings before aggregating.
-- Dialect: PostgreSQL
