-- Title: 2nd Ride Delay
-- Company: Uber
-- Difficulty: Medium
-- Access: Premium
-- Pattern: window function (ROW_NUMBER/LAG) + time difference
-- Summary: Order rides per user and compute the time gap between the first and second ride (or isolate the 2nd ride delay).
-- Notes: Use ROW_NUMBER to pick rides 1 and 2; ensure timestamp math uses correct units; handle users with <2 rides.
-- Dialect: PostgreSQL
