-- Title: Google Maps Flagged UGC
-- Company: Google
-- Difficulty: Medium
-- Access: Premium
-- Pattern: filtering + aggregation by status
-- Summary: Filter to flagged user-generated content and aggregate counts/percentages by reason/status as required.
-- Notes: Confirm what qualifies as “flagged” (boolean vs status code); use DISTINCT if joins can duplicate UGC records.
-- Dialect: PostgreSQL
