-- Title: LinkedIn Power Creators (Part 2)
-- Company: LinkedIn
-- Difficulty: Medium
-- Access: Premium
-- Pattern: window ranking + thresholds
-- Summary: Rank creators by engagement metrics and filter to those meeting power-creator criteria using window functions and HAVING/WHERE.
-- Notes: Use DENSE_RANK for ties; confirm metric definitions and time window; deduplicate engagement events if needed.
-- Dialect: PostgreSQL
