-- Title: Unique Money Transfer Relationships
-- Company: PayPal
-- Difficulty: Medium
-- Access: Premium
-- Pattern: pair normalization + distinct counting
-- Summary: Count unique transfer relationships by normalizing sender/receiver pairs and counting distinct pairs.
-- Notes: Use LEAST/GREATEST (or CASE) to make pairs order-independent; exclude self-transfers if required.
-- Dialect: PostgreSQL
