-- Title: User Session Activity
-- Company: Twitter
-- Difficulty: Medium
-- Access: Premium
-- Pattern: sessionization (time-gap grouping)
-- Summary: Build sessions per user by grouping events where gaps exceed a threshold, then aggregate activity per session.
-- Notes: Use LAG to compute gaps and a running SUM to assign session_id; confirm session gap threshold and units.
-- Dialect: PostgreSQL
