-- Title: First Transaction
-- Company: Etsy
-- Difficulty: Medium
-- Access: Premium
-- Pattern: window function (ROW_NUMBER) / MIN per group
-- Summary: Identify each user’s first transaction by ordering transactions and selecting the earliest one.
-- Notes: Use ROW_NUMBER ordered by timestamp (plus id for tie-break); users with multiple same-time transactions need deterministic ordering.
-- Dialect: PostgreSQL
