-- Title: Email Table Transformation
-- Company: Facebook
-- Difficulty: Medium
-- Access: Premium
-- Pattern: transformations (pivot / normalization)
-- Summary: Transform the email table into the required shape using CASE-based pivoting or conditional aggregation.
-- Notes: Use MAX(CASE...) for pivot columns; ensure one row per entity after transformation; handle NULLs with COALESCE if needed.
-- Dialect: PostgreSQL
