-- Title: Photoshop Revenue Analysis
-- Company: Adobe
-- Difficulty: Medium
-- Access: Premium
-- Pattern: aggregation + filtering by product
-- Summary: Filter revenue to Photoshop (or its SKU) and compute the requested revenue metrics by the required dimension.
-- Notes: Watch for product naming variants; if joining orders to products, avoid double-counting with DISTINCT order ids.
-- Dialect: PostgreSQL
