-- Title: Consulting Bench Time
-- Company: Google
-- Difficulty: Medium
-- Access: Premium
-- Pattern: date range math + gaps (bench time)
-- Summary: Calculate bench time by measuring gaps between staffed project intervals per consultant and summing unassigned days.
-- Notes: Sort intervals carefully; clamp overlaps to avoid negative gaps; handle first/last interval boundaries per definition.
-- Dialect: PostgreSQL
