-- Title: Sales Team Compensation
-- Company: Oracle
-- Difficulty: Medium
-- Access: Premium
-- Pattern: aggregation + business rules
-- Summary: Compute compensation by applying commission/bonus rules to sales aggregates and returning payout per rep.
-- Notes: Encode rules with CASE; verify tiers and thresholds; use COALESCE for missing components.
-- Dialect: PostgreSQL
