-- Title: Average Deal Size (Part 2)
-- Company: Salesforce
-- Difficulty: Medium
-- Access: Premium
-- Pattern: aggregation + segmented averages
-- Summary: Compute average deal size by grouping deals by stage/owner/segment and taking AVG of deal amounts.
-- Notes: Filter to closed/won as required; use AVG(amount::numeric) if needed; exclude NULL/0 deals depending on definition.
-- Dialect: PostgreSQL
