-- Title: Cumulative Purchases by Product Type
-- Company: Amazon
-- Difficulty: Medium
-- Access: Premium
-- Pattern: window function (running total)
-- Summary: Compute running totals of purchases per product type over time using SUM(...) OVER (PARTITION BY ... ORDER BY ...).
-- Notes: Ensure correct ordering by date; choose ROWS vs RANGE depending on data grain; fill missing dates only if required.
-- Dialect: PostgreSQL
