-- Title: Compensation Outliers
-- Company: Accenture
-- Difficulty: Medium
-- Access: Premium
-- Pattern: statistical thresholds (IQR/z-score)
-- Summary: Detect compensation outliers by computing a benchmark distribution and filtering salaries outside the threshold.
-- Notes: IQR uses percentiles (PERCENTILE_CONT); ensure thresholds match definition; handle small groups carefully.
-- Dialect: PostgreSQL
