-- Title: FAANG Stock Monthly Change (Part 2)
-- Company: Bloomberg
-- Difficulty: Medium
-- Access: Premium
-- Pattern: time series (LAG) + percent change
-- Summary: Compute month-over-month stock changes by comparing each month’s value to the prior month using LAG.
-- Notes: Aggregate to monthly grain first (e.g., month-end price); cast to numeric and use NULLIF to avoid divide-by-zero.
-- Dialect: PostgreSQL
